//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace Framework.MobileServiceManager {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MobileServiceManagerHttpBinding", Namespace="http://mobile.server.scpwms.core.com")]
    public partial class MobileServiceManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MobileServiceManager() {
            this.Url = "http://192.168.1.101:9097/scpwms/webService/MobileServiceManager";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executeCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executeCount", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteCount(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeCount", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecuteCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executeCsPick([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executeCsPick", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteCsPick(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeCsPick", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecuteCsPick(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string searchInventory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("searchInventory", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchInventory(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchInventory", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsearchInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getNextPickInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getNextPickInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetNextPickInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getNextPickInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetNextPickInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getPsPickInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getPsPickInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPsPickInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPsPickInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPsPickInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string searchAsn([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("searchAsn", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchAsn(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchAsn", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsearchAsn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executePsPick([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executePsPick", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecutePsPick(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executePsPick", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecutePsPick(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string startMultiAsn([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("startMultiAsn", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstartMultiAsn(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("startMultiAsn", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndstartMultiAsn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getCountInfoByQr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getCountInfoByQr", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCountInfoByQr(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCountInfoByQr", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCountInfoByQr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executeBatchPick([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executeBatchPick", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteBatchPick(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeBatchPick", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecuteBatchPick(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string searchWaveDoc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("searchWaveDoc", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchWaveDoc(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchWaveDoc", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsearchWaveDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getAsnDetailBySku([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getAsnDetailBySku", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAsnDetailBySku(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAsnDetailBySku", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAsnDetailBySku(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getInvDetailInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getInvDetailInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInvDetailInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInvDetailInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInvDetailInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getCsPickInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getCsPickInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCsPickInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCsPickInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCsPickInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getInvInfoByQr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getInvInfoByQr", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInvInfoByQr(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInvInfoByQr", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInvInfoByQr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("login", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string startPsPick([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("startPsPick", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstartPsPick(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("startPsPick", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndstartPsPick(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getInvInfoByBinCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getInvInfoByBinCode", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInvInfoByBinCode(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInvInfoByBinCode", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInvInfoByBinCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getSkuId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getSkuId", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSkuId(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSkuId", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSkuId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getAsnIdBySku4Multi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getAsnIdBySku4Multi", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAsnIdBySku4Multi(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAsnIdBySku4Multi", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAsnIdBySku4Multi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string searchCountPlan([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("searchCountPlan", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchCountPlan(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchCountPlan", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsearchCountPlan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executeInvMove([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executeInvMove", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteInvMove(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeInvMove", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecuteInvMove(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string checkBin4Count([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("checkBin4Count", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckBin4Count(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkBin4Count", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckBin4Count(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getCaseInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getCaseInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCaseInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCaseInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCaseInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getPickInfo4Batch([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getPickInfo4Batch", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPickInfo4Batch(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPickInfo4Batch", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPickInfo4Batch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getAsnInfo4Multi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getAsnInfo4Multi", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAsnInfo4Multi(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAsnInfo4Multi", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAsnInfo4Multi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getSkuInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getSkuInfo", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSkuInfo(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSkuInfo", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSkuInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string receiveAsnDetail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("receiveAsnDetail", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreceiveAsnDetail(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("receiveAsnDetail", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreceiveAsnDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string checkedCase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("checkedCase", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckedCase(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkedCase", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckedCase(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getOwnerList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getOwnerList", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOwnerList(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOwnerList", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetOwnerList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string executeBinMove([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("executeBinMove", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteBinMove(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeBinMove", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexecuteBinMove(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string helloMobile([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("helloMobile", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhelloMobile(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("helloMobile", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndhelloMobile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mobile.server.scpwms.core.com", ResponseNamespace="http://mobile.server.scpwms.core.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string printAsnLabel([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("printAsnLabel", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprintAsnLabel(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("printAsnLabel", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndprintAsnLabel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
